set(_CATKIN_CURRENT_PACKAGE "joint_space_planner_awm14")
set(joint_space_planner_awm14_MAINTAINER "guest <guest@todo.todo>")
set(joint_space_planner_awm14_DEPRECATED "")
set(joint_space_planner_awm14_VERSION "0.0.0")
set(joint_space_planner_awm14_BUILD_DEPENDS "roscpp" "atlas_conversions" "atlas_msgs" "trajectory_msgs" "actionlib" "actionlib_msgs" "eigen" "hku_msgs" "tf" "geometry_msgs" "atlas_hand_kinematics" "actionlib_servers" "kdl" "kdl_parser" "message_generation" "orocos_kdl" "task_variables" "jacobian_publisher" "manipulation_balancing" "example_wall_cutting" "std" "roslib" "lljc" "low_level_joint_controller" "std_msgs" "simple_action_client" "eigen_to_msg")
set(joint_space_planner_awm14_RUN_DEPENDS "simple_action_client" "std_msgs" "roscpp" "atlas_conversions" "atlas_msgs" "trajectory_msgs" "actionlib" "actionlib_msgs" "eigen" "hku_msgs" "tf" "geometry_msgs" "atlas_hand_kinematics" "actionlib_servers" "kdl" "kdl_parser" "message_runtime" "orocos_kdl" "task_variables" "std" "roslib" "jacobian_publisher" "eigen_to_msg" "example_wall_cutting")
set(joint_space_planner_awm14_BUILDTOOL_DEPENDS "catkin" "catkin_simple")