set(_CATKIN_CURRENT_PACKAGE "test_joint_space_client")
set(test_joint_space_client_MAINTAINER "guest <guest@todo.todo>")
set(test_joint_space_client_DEPRECATED "")
set(test_joint_space_client_VERSION "0.0.0")
set(test_joint_space_client_BUILD_DEPENDS "roscpp" "actionlib" "geometry_msgs" "eigen_to_msg" "eigen")
set(test_joint_space_client_RUN_DEPENDS "roscpp" "actionlib" "geometry_msgs" "eigen_to_msg" "eigen")
set(test_joint_space_client_BUILDTOOL_DEPENDS "catkin" "catkin_simple")